POST http://localhost:8000/api/transactions/
Content-Type: application/json
Accept: application/json

{
  "text": "Salaire du mois percu",
  "amount": -2000.00
}

###
GET http://localhost:8000/api/transactions/
Accept: application/json


###
DELETE http://localhost:8000/api/transactions/81292fcf-40e0-487d-8659-72f4227f2d3a/
Accept: application/json

###
PUT http://localhost:8000/api/transactions/150de692-f541-4d66-b5a7-1f39dbaab810/
Content-Type: application/json
Accept: application/json

{
  "text": "Salaire fevrier",
  "amount": 10000.00
}

###
PATCH http://localhost:8000/api/transactions/150de692-f541-4d66-b5a7-1f39dbaab810/
Content-Type: application/json
Accept: application/json

{
  "amount": 12000.00
}

